'use strict';

(function () {
  window.constants = {
    ESC_KEYCODE: 27,
    ENTER_KEYCODE: 13,
    PICTURES: 25,
    LIKE_MINCOUNTS: 15,
    LIKE_MAXCOUNTS: 200,
    RANGE_MAXCOORD: 455,
    BLUR_MAXVALUE: 5,
    BRIGHTNESS_MAXVALUE: 3,
    PERCENT_MAXVALUE: 100,
    HASHTAG_MAXLENGTH: 20,
    INITIAL_INPUT_VALUE: 20,
    HALF_FILTERHANDLE: 9,
    SERVER_TIMEOUT: 15000,
    SERVER_STATUS_SUCCESS: 200,
    URL: 'https://1510.dump.academy/kekstagram'
  };
})();
